import { TimeSeriesConfig } from "../types/index.js";

// Time Series Structure
export const TIME_SERIES_STRUCTURE = {
  timeSeriesBuckets: [
    {
      id: "stats_realtime",
      name: "stats_realtime",
      resolution: "10s",
      retention: "1h",
      timeRange: "now - 1h",
      maxRows: 360,
      description: "Highest resolution data for the last hour",
    },
    {
      id: "stats_5m",
      name: "stats_5m",
      resolution: "5m",
      retention: "2h",
      timeRange: "1h - 3h ago",
      maxRows: 24,
      description: "Medium-high resolution data for 1-3 hours ago",
    },
    {
      id: "stats_10m",
      name: "stats_10m",
      resolution: "10m",
      retention: "3h",
      timeRange: "3h - 6h ago",
      maxRows: 18,
      description: "Medium resolution data for 3-6 hours ago",
    },
    {
      id: "stats_15m",
      name: "stats_15m",
      resolution: "15m",
      retention: "6h",
      timeRange: "6h - 12h ago",
      maxRows: 24,
      description: "Medium resolution data for 6-12 hours ago",
    },
    {
      id: "stats_30m",
      name: "stats_30m",
      resolution: "30m",
      retention: "12h",
      timeRange: "12h - 24h ago",
      maxRows: 24,
      description: "Medium-low resolution data for 12-24 hours ago",
    },
    {
      id: "stats_1h",
      name: "stats_1h",
      resolution: "1h",
      retention: "24h",
      timeRange: "24h - 48h ago",
      maxRows: 24,
      description: "Hourly data for 1-2 days ago",
    },
    {
      id: "stats_3h",
      name: "stats_3h",
      resolution: "3h",
      retention: "48h",
      timeRange: "48h - 96h ago",
      maxRows: 16,
      description: "3-hour intervals for 2-4 days ago",
    },
    {
      id: "stats_6h",
      name: "stats_6h",
      resolution: "6h",
      retention: "3d",
      timeRange: "4d - 7d ago",
      maxRows: 12,
      description: "6-hour intervals for 4-7 days ago",
    },
    {
      id: "stats_9h",
      name: "stats_9h",
      resolution: "9h",
      retention: "7d",
      timeRange: "7d - 14d ago",
      maxRows: 19,
      description: "9-hour intervals for 7-14 days ago",
    },
    {
      id: "stats_12h",
      name: "stats_12h",
      resolution: "12h",
      retention: "16d",
      timeRange: "14d - 30d ago",
      maxRows: 32,
      description: "12-hour intervals for 14-30 days ago",
    },
  ],
};

export const TIME_SERIES_CONFIGS: TimeSeriesConfig[] = [
  {
    id: "stats_realtime",
    name: "stats_realtime",
    retention: "60m", // 1 hour
    resolution: "10s",
    startFrom: "0m",
    until: "60m",
  },
  {
    id: "stats_5m",
    name: "stats_5m",
    retention: "6h",
    resolution: "5m",
    startFrom: "1h",
    until: "3h",
  },
  {
    id: "stats_10m",
    name: "stats_10m",
    retention: "6h",
    resolution: "10m",
    startFrom: "3h",
    until: "6h",
  },
  {
    id: "stats_15m",
    name: "stats_15m",
    retention: "12h",
    resolution: "15m",
    startFrom: "6h",
    until: "12h",
  },
  {
    id: "stats_30m",
    name: "stats_30m",
    retention: "24h",
    resolution: "30m",
    startFrom: "12h",
    until: "24h",
  },
  {
    id: "stats_1h",
    name: "stats_1h",
    retention: "48h",
    resolution: "1h",
    startFrom: "24h",
    until: "48h",
  },
  {
    id: "stats_3h",
    name: "stats_3h",
    retention: "96h",
    resolution: "3h",
    startFrom: "48h",
    until: "96h",
  },
  {
    id: "stats_6h",
    name: "stats_6h",
    retention: "7d",
    resolution: "6h",
    startFrom: "96h",
    until: "7d",
  },
  {
    id: "stats_9h",
    name: "stats_9h",
    retention: "14d",
    resolution: "9h",
    startFrom: "7d",
    until: "14d",
  },
  {
    id: "stats_12h",
    name: "stats_12h",
    retention: "30d",
    resolution: "12h",
    startFrom: "14d",
    until: "30d",
  },
];
