services:
  node-app:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
      - POCKETBASE_ADMIN_EMAIL=fr.barbre@gmail.com
      - POCKETBASE_ADMIN_PASSWORD=Cecilieharbo69
    networks:
      - app-network
    depends_on:
      pocketbase:
        condition: service_healthy

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb_data
      - ./backend/pb_migrations:/pb_migrations
    networks:
      - app-network
    environment:
      - POCKETBASE_ADMIN_EMAIL=fr.barbre@gmail.com
      - POCKETBASE_ADMIN_PASSWORD=Cecilieharbo69
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8090/api/health",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  app-network:
    driver: bridge

volumes:
  pocketbase_data:
